# Generated by Django 5.0.6 on 2024-05-26 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custumers', '0002_config_active_custumerhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('pay_date', models.DateField()),
                ('confirmation', models.PositiveIntegerField(default=0)),
                ('deny_reason', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='custumers.customer')),
            ],
        ),
    ]
