# Generated by Django 5.0.6 on 2024-05-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='config_in_queue',
            field=models.BooleanField(default=False),
        ),
    ]
