# Generated by Django 5.0.6 on 2024-05-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='user_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
