# Generated by Django 5.0.6 on 2024-05-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_prices_user_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
