# Generated by Django 5.0.6 on 2024-05-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_payment_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='confirmation',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='payment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
