# Generated by Django 5.0.6 on 2024-05-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_rename_confirmation_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='deny_reason',
        ),
    ]
