# Generated by Django 5.0.6 on 2024-05-29 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custumers', '0010_customer_pay_temp_amount'),
        ('finance', '0007_remove_payment_deny_reason'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='ConfirmPaymentQueue',
        ),
    ]
