# Generated by Django 5.0.6 on 2024-05-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_rename_payment_confirmpaymentqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmpaymentqueue',
            name='config_uuid',
            field=models.UUIDField(blank=True, default='e5b5108a-14c8-454b-ac86-21d149610755', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confirmpaymentqueue',
            name='deny_reseon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
