# Generated by Django 5.0.6 on 2024-05-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_confirmpaymentqueue_config_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmpaymentqueue',
            name='config_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
