# Generated by Django 5.0.6 on 2024-05-29 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_rename_amount_confirmpaymentqueue_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmpaymentqueue',
            old_name='user',
            new_name='userid',
        ),
    ]
