# Generated by Django 5.0.6 on 2024-05-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_rename_user_confirmpaymentqueue_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmpaymentqueue',
            name='pay_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
