# Generated by Django 5.0.6 on 2024-05-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_confirmpaymentqueue_pay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmpaymentqueue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_images/'),
        ),
    ]
