# Generated by Django 5.0.6 on 2024-06-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_rename_price_confirmpaymentqueue_pay_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmpaymentqueue',
            name='config_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
