# Generated by Django 5.0.6 on 2024-06-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_confirmpaymentqueue_config_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmpaymentqueue',
            name='config_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
