# Generated by Django 5.0.6 on 2024-06-21 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_alter_confirmpaymentqueue_config_price'),
        ('servers', '0022_tamdidconfigqueue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmTamdidPaymentQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_price', models.PositiveIntegerField()),
                ('config_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('status', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='payment_images/')),
                ('deny_reseon', models.CharField(blank=True, max_length=100, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.configsinfo')),
            ],
        ),
    ]
