# Generated by Django 5.0.6 on 2024-06-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_confirmtamdidpaymentqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmpaymentqueue',
            name='timestamp',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='confirmtamdidpaymentqueue',
            name='timestamp',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
