# Generated by Django 5.0.6 on 2024-07-09 15:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumers', '0022_remove_customer_restrict'),
        ('finance', '0020_confirmpaymentqueue_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type_off', models.BooleanField()),
                ('amount', models.PositiveIntegerField()),
                ('curumer_count', models.PositiveIntegerField()),
                ('use_count', models.PositiveIntegerField()),
                ('create_timestamp', models.PositiveBigIntegerField()),
                ('end_timestamp', models.PositiveBigIntegerField()),
                ('for_infinit_usages', models.BooleanField()),
                ('for_infinit_times', models.BooleanField()),
                ('for_not_infinity', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserActiveOffCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custumer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='custumers.customer')),
                ('off_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.offcodes')),
            ],
        ),
    ]
