# Generated by Django 5.0.6 on 2024-07-09 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_offcodes_useractiveoffcodes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offcodes',
            old_name='curumer_count',
            new_name='customer_count',
        ),
    ]
