# Generated by Django 5.0.6 on 2024-07-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_useractiveoffcodes_used_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractiveoffcodes',
            name='used_time',
        ),
        migrations.AddField(
            model_name='useractiveoffcodes',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
