# Generated by Django 5.0.6 on 2024-05-26 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='CustumerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_user', models.CharField(max_length=50)),
                ('record_date', models.DateTimeField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='custumers.customer')),
            ],
        ),
    ]
