# Generated by Django 5.0.6 on 2024-05-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumers', '0004_alter_customer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='test_config',
            field=models.BooleanField(default=False),
        ),
    ]
