# Generated by Django 5.0.6 on 2024-05-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumers', '0006_alter_customer_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='userid',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
