# Generated by Django 5.0.6 on 2024-05-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumers', '0007_alter_customer_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='temp_status',
            field=models.CharField(default='set_pay_amount', max_length=30),
        ),
    ]
