# Generated by Django 5.0.6 on 2024-05-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumers', '0008_customer_temp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='temp_status',
            field=models.CharField(default='normal', max_length=30),
        ),
    ]
