# Generated by Django 5.0.6 on 2024-05-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumers', '0009_alter_customer_temp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pay_temp_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
