# Generated by Django 5.0.6 on 2024-05-29 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custumers', '0010_customer_pay_temp_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config',
        ),
    ]
