# Generated by Django 5.0.6 on 2024-05-30 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custumers', '0011_delete_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custumerhistory',
            old_name='userid',
            new_name='custumer',
        ),
    ]
