# Generated by Django 5.0.6 on 2024-06-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumers', '0012_rename_userid_custumerhistory_custumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
