# Generated by Django 5.0.6 on 2024-06-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumers', '0013_customer_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='restrict',
            field=models.BooleanField(default=False),
        ),
    ]
