# Generated by Django 5.0.6 on 2024-06-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumers', '0015_alter_customer_first_name_alter_customer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='get_test',
            field=models.BooleanField(default=False),
        ),
    ]
