# Generated by Django 5.0.6 on 2024-06-29 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custumers', '0016_customer_get_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='get_test',
        ),
    ]
