# Generated by Django 5.0.6 on 2024-06-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumers', '0017_remove_customer_get_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='change_location_time',
            field=models.IntegerField(default=0),
        ),
    ]
