# Generated by Django 5.0.6 on 2024-06-29 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custumers', '0018_customer_change_location_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='change_location_time',
        ),
    ]
