# Generated by Django 5.0.6 on 2024-07-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumers', '0019_remove_customer_change_location_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='userid',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
