# Generated by Django 5.0.6 on 2024-07-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumers', '0020_alter_customer_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='userid',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
