# Generated by Django 5.0.6 on 2024-07-05 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custumers', '0021_alter_customer_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='restrict',
        ),
    ]
