# Generated by Django 5.0.6 on 2024-06-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0021_msgendofconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='createconfigqueue',
            name='for_tamdid',
            field=models.BooleanField(default=False),
        ),
    ]
