# Generated by Django 5.0.6 on 2024-06-21 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumers', '0013_customer_active'),
        ('servers', '0022_createconfigqueue_for_tamdid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createconfigqueue',
            name='for_tamdid',
        ),
        migrations.CreateModel(
            name='TamdidConfigQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_uuid', models.UUIDField(unique=True)),
                ('config_name', models.CharField(max_length=50, unique=True)),
                ('usage_limit', models.IntegerField()),
                ('expire_time', models.IntegerField()),
                ('user_limit', models.IntegerField()),
                ('price', models.IntegerField()),
                ('sent_to_user', models.IntegerField(default=0)),
                ('pay_status', models.PositiveSmallIntegerField(default=0)),
                ('custumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custumers.customer')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.server')),
            ],
        ),
    ]
