# Generated by Django 5.0.6 on 2024-06-21 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0023_remove_createconfigqueue_for_tamdid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tamdidconfigqueue',
            name='config_name',
        ),
        migrations.RemoveField(
            model_name='tamdidconfigqueue',
            name='config_uuid',
        ),
        migrations.RemoveField(
            model_name='tamdidconfigqueue',
            name='custumer',
        ),
        migrations.RemoveField(
            model_name='tamdidconfigqueue',
            name='server',
        ),
        migrations.AddField(
            model_name='tamdidconfigqueue',
            name='config',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='servers.configsinfo'),
            preserve_default=False,
        ),
    ]
