# Generated by Django 5.0.6 on 2024-06-27 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custumers', '0014_customer_restrict'),
        ('servers', '0024_infinitcongislimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.CharField(max_length=15)),
                ('action', models.TextField()),
                ('timestamp', models.IntegerField(default=1719481277)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('timestamp', models.IntegerField(default=1719481277)),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='servers.configsinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('timestamp', models.IntegerField(default=1719481277)),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='custumers.customer')),
            ],
        ),
    ]
