# Generated by Django 5.0.6 on 2024-06-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerlog',
            old_name='config',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='timestamp',
            field=models.IntegerField(default=1719482083),
        ),
        migrations.AlterField(
            model_name='configlog',
            name='timestamp',
            field=models.IntegerField(default=1719482083),
        ),
        migrations.AlterField(
            model_name='customerlog',
            name='timestamp',
            field=models.IntegerField(default=1719482083),
        ),
    ]
