# Generated by Django 5.0.6 on 2024-06-27 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumers', '0015_alter_customer_first_name_alter_customer_username'),
        ('reports', '0005_alter_adminlog_timestamp_alter_configlog_timestamp_and_more'),
        ('servers', '0024_infinitcongislimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configlog',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.configsinfo'),
        ),
        migrations.AlterField(
            model_name='customerlog',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custumers.customer'),
        ),
    ]
