# Generated by Django 5.0.6 on 2024-06-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_configlog_config_alter_customerlog_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.TextField()),
                ('timestamp', models.IntegerField()),
            ],
        ),
    ]
