# Generated by Django 5.0.6 on 2024-07-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_errorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryDeleteConfigLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('userid', models.PositiveBigIntegerField(null=True)),
                ('timestamp', models.IntegerField(default=1719482579)),
            ],
        ),
    ]
