# Generated by Django 5.0.6 on 2024-05-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('server_username', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('server_name', models.CharField(max_length=20)),
                ('server_url', models.URLField()),
                ('inbound_id', models.IntegerField()),
                ('inbound_port', models.IntegerField()),
            ],
        ),
    ]
