# Generated by Django 5.0.6 on 2024-05-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_server_server_fake_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_fake_domain',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
