# Generated by Django 5.0.6 on 2024-05-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_alter_server_server_fake_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='password',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
