# Generated by Django 5.0.6 on 2024-05-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_rename_server_username_server_server_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
