# Generated by Django 5.0.6 on 2024-05-29 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0007_alter_server_server_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateConfigQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_uuid', models.UUIDField(unique=True)),
                ('config_name', models.CharField(max_length=50)),
                ('usage_limit', models.IntegerField()),
                ('expire_time', models.IntegerField()),
                ('user_limit', models.IntegerField()),
                ('price', models.IntegerField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.server')),
            ],
        ),
    ]
