# Generated by Django 5.0.6 on 2024-05-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0008_createconfigqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createconfigqueue',
            name='config_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
