# Generated by Django 5.0.6 on 2024-05-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0009_alter_createconfigqueue_config_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='createconfigqueue',
            name='sent_to_user',
            field=models.BooleanField(default=False),
        ),
    ]
