# Generated by Django 5.0.6 on 2024-05-29 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumers', '0011_delete_config'),
        ('servers', '0011_createconfigqueue_pay_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='createconfigqueue',
            name='userid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='custumers.customer'),
            preserve_default=False,
        ),
    ]
