# Generated by Django 5.0.6 on 2024-05-30 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0012_createconfigqueue_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createconfigqueue',
            old_name='userid',
            new_name='custumer',
        ),
    ]
