# Generated by Django 5.0.6 on 2024-05-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0014_remove_createconfigqueue_pay_confirm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createconfigqueue',
            name='pay_status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
