# Generated by Django 5.0.6 on 2024-06-03 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumers', '0012_rename_userid_custumerhistory_custumer'),
        ('servers', '0015_alter_createconfigqueue_pay_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(max_length=25, unique=True)),
                ('config_uuid', models.UUIDField(unique=True)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='custumers.customer')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='servers.server')),
            ],
        ),
    ]
