# Generated by Django 5.0.6 on 2024-06-09 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumers', '0013_customer_active'),
        ('servers', '0017_alter_createconfigqueue_sent_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configsinfo',
            name='chat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='custumers.customer'),
        ),
    ]
