# Generated by Django 5.0.6 on 2024-06-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0018_alter_configsinfo_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='configsinfo',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
