# Generated by Django 5.0.6 on 2024-06-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0019_configsinfo_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='configsinfo',
            name='created_by',
            field=models.CharField(default='BOT', max_length=20),
        ),
        migrations.AddField(
            model_name='configsinfo',
            name='paid',
            field=models.BooleanField(default=True),
        ),
    ]
