# Generated by Django 5.0.6 on 2024-06-20 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0020_configsinfo_created_by_configsinfo_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsgEndOfConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('almost_time', models.BooleanField(default=False)),
                ('almost_usage', models.BooleanField(default=False)),
                ('ended_time', models.BooleanField(default=False)),
                ('ended_usage', models.BooleanField(default=False)),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='servers.configsinfo')),
            ],
        ),
    ]
