# Generated by Django 5.0.6 on 2024-06-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0022_tamdidconfigqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='configsinfo',
            name='renew_count',
            field=models.IntegerField(default=0),
        ),
    ]
