# Generated by Django 5.0.6 on 2024-06-27 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0023_configsinfo_renew_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfinitCongisLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField()),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='servers.configsinfo')),
            ],
        ),
    ]
