# Generated by Django 5.0.6 on 2024-06-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0025_server_iphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='configsinfo',
            name='change_location_time',
            field=models.IntegerField(default=0),
        ),
    ]
