# Generated by Django 5.0.6 on 2024-06-30 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumers', '0019_remove_customer_change_location_time'),
        ('servers', '0026_configsinfo_change_location_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(max_length=25, unique=True)),
                ('config_uuid', models.UUIDField(unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='custumers.customer')),
            ],
        ),
    ]
