# Generated by Django 5.0.6 on 2024-07-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0027_testconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='testconfig',
            name='sent_notif',
            field=models.BooleanField(default=False),
        ),
    ]
