# Generated by Django 5.0.6 on 2024-07-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0028_testconfig_sent_notif'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MsgEndOfConfig',
        ),
    ]
