# Generated by Django 5.0.6 on 2024-06-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendmessage',
            name='id',
        ),
        migrations.AddField(
            model_name='sendmessage',
            name='uuid',
            field=models.UUIDField(default='0c896661-0319-478d-8bc7-8f973005eebf', editable=False, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
