# Generated by Django 5.0.6 on 2024-06-07 17:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_remove_sendmessage_id_sendmessage_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
