# Generated by Django 5.0.6 on 2024-06-07 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0007_alter_sendmessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
