# Generated by Django 5.0.6 on 2024-06-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0008_sendmessage_created_at_sendmessage_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndOfConfigCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('type', models.CharField(choices=[(0, 'ended'), (1, 'end_of_usage'), (2, 'end_of_time')], max_length=20)),
                ('data_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
