# Generated by Django 5.0.6 on 2024-06-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0009_endofconfigcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='endofconfigcounter',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
