# Generated by Django 5.0.6 on 2024-06-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0011_alter_endofconfigcounter_data_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endofconfigcounter',
            name='data_time',
        ),
        migrations.AddField(
            model_name='endofconfigcounter',
            name='timestamp',
            field=models.IntegerField(default=1719316174),
        ),
    ]
