# Generated by Django 5.0.6 on 2024-06-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0012_remove_endofconfigcounter_data_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endofconfigcounter',
            name='count',
        ),
        migrations.AlterField(
            model_name='endofconfigcounter',
            name='timestamp',
            field=models.IntegerField(default=1719316668),
        ),
    ]
