# Generated by Django 5.0.6 on 2024-06-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0013_remove_endofconfigcounter_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endofconfigcounter',
            name='timestamp',
            field=models.IntegerField(default=1719472738),
        ),
    ]
