# Generated by Django 5.0.6 on 2024-06-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0016_alter_endofconfigcounter_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endofconfigcounter',
            name='timestamp',
            field=models.IntegerField(default=1719482431),
        ),
    ]
