# Generated by Django 5.0.6 on 2024-06-27 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0018_alter_endofconfigcounter_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endofconfigcounter',
            name='timestamp',
        ),
    ]
