# Generated by Django 5.0.6 on 2024-07-03 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0020_endofconfigcounter_timestamp'),
        ('servers', '0028_testconfig_sent_notif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endofconfigcounter',
            name='uuid',
        ),
        migrations.AddField(
            model_name='endofconfigcounter',
            name='config',
            field=models.ForeignKey(default=434, on_delete=django.db.models.deletion.CASCADE, to='servers.configsinfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endofconfigcounter',
            name='timestamp',
            field=models.IntegerField(default=0),
        ),
    ]
